### ISSUE TITLE
Remove dependency on libc

### ISSUE THREAD

**Issue by jmillikin** [jmillikin/rust-fuse#11]
- [x] Replace calls to `libc::mount()`, `libc::getuid()`, etc with raw syscalls.
- [x] Use https://github.com/rust-lang/rfcs/pull/2973 or hardcoded target-specific values for POSIX error numbers.

libstd currently depends on libc, so until that's fixed also allow rust-fuse to be optionally `#![no_std]`:
- [x] Change `FuseMount` to return `Channel` rather than `std::fs::File`.
- [x] Verify that a `#![no_std]` binary linking with `rlibc` can produce working FUSE servers.

**Comment by lzutao** [comment]
FYI, `libc` also is a no_std crate by disable the `std` feature.
